<?php
include('db.php');
session_start();
if (!isset($_SESSION['user_id'])) {
    header("Location: login.php");
    exit();
}
if (!isset($_GET['id'])) {
    die("<script>alert('No payment ID found.'); window.location='tenant_dashboard.php';</script>");
}

$payment_id = mysqli_real_escape_string($conn, $_GET['id']);
$sql = "SELECT p.*, u.full_name, un.unit_no 
        FROM bills p 
        JOIN users u ON p.user_id = u.id 
        JOIN units un ON p.unit_id = un.id 
        WHERE p.id = '$payment_id' AND p.status = 'Approved'";

$result = mysqli_query($conn, $sql);
$receipt = mysqli_fetch_assoc($result);
if (!$receipt) {
    die("<div style='text-align:center; margin-top:50px;'>
            <h2>Receipt Not Available</h2>
            <p>This payment is either pending verification or does not exist.</p>
            <a href='tenant_dashboard.php'>Go Back</a>
         </div>");
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Official Receipt - #<?php echo $receipt['id']; ?></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body { background-color: #f8f9fa; font-family: 'Courier New', Courier, monospace; }
        .receipt-paper {
            background: white;
            max-width: 500px;
            margin: 30px auto;
            padding: 30px;
            border: 1px solid #eee;
            box-shadow: 0 0 15px rgba(0,0,0,0.1);
            position: relative;
        }
        .header-logo { font-size: 24px; font-weight: bold; color: #2c3e50; }
        .dashed-line { border-top: 2px dashed #ccc; margin: 15px 0; }
        .amount-box { border: 2px solid #000; padding: 10px; display: inline-block; font-size: 20px; font-weight: bold; }
        
        /* PARA SA PRINTING: Tatanggalin ang buttons sa papel */
        @media print {
            .no-print { display: none !important; }
            .receipt-paper { box-shadow: none; border: none; margin: 0 auto; }
            body { background: white; }
        }
    </style>
</head>
<body>

<div class="container text-center mt-4 no-print">
    <button onclick="window.print()" class="btn btn-success px-4 me-2">
        <i class="fa fa-print"></i> PRINT NOW
    </button>
    <button onclick="window.history.back()" class="btn btn-outline-secondary px-4">
        BACK
    </button>
</div>

<div class="receipt-paper">
    <div class="text-center">
        <div class="header-logo">MG'S TENANT</div>
        <p class="small mb-0">Tenant Management System</p>
        <p class="small">Contact: 0912-345-6789</p>
    </div>

    <div class="dashed-line"></div>

    <div class="row small mb-3">
        <div class="col-6">
            <strong>OR NO:</strong> #PAY-<?php echo str_pad($receipt['id'], 6, '0', STR_PAD_LEFT); ?>
        </div>
        <div class="col-6 text-end">
            <strong>DATE:</strong> <?php echo date('M d, Y', strtotime($receipt['date_paid'])); ?>
        </div>
    </div>

    <div class="mb-3">
        <p class="mb-1 text-muted small">RECEIVED FROM:</p>
        <h5 class="fw-bold border-bottom pb-1 text-uppercase"><?php echo $receipt['full_name']; ?></h5>
    </div>

    <div class="mb-4">
        <table class="table table-borderless table-sm small">
            <tr>
                <td>Payment for Unit:</td>
                <td class="text-end fw-bold">Unit <?php echo $receipt['unit_no']; ?></td>
            </tr>
            <tr>
                <td>Payment Mode:</td>
                <td class="text-end">GCash / Online</td>
            </tr>
            <tr>
                <td>GCash Ref No:</td>
                <td class="text-end fw-bold text-primary"><?php echo $receipt['ref_no']; ?></td>
            </tr>
        </table>
    </div>

    <div class="text-center mb-4">
        <div class="amount-box">
            PHP <?php echo number_format($receipt['amount'], 2); ?>
        </div>
        <p class="small text-success mt-2 fw-bold">PAID IN FULL</p>
    </div>

    <div class="dashed-line"></div>

    <div class="row mt-4">
        <div class="col-6 text-center">
            <div class="small text-muted">Issued By:</div>
            <div class="mt-3 border-top pt-1 fw-bold small">MG LANDLORD</div>
        </div>
        <div class="col-6 text-center">
            <div class="small text-muted">Status:</div>
            <div class="mt-3 text-success fw-bold small">VERIFIED</div>
        </div>
    </div>

    <p class="text-center mt-4 small text-muted italic" style="font-size: 10px;">
        This is an official digital receipt generated by MG's Tenant System.
    </p>
</div>

<script src="https://kit.fontawesome.com/a076d05399.js" crossorigin="anonymous"></script>
</body>
</html>